import awkward as ak
import numpy as np

# mu_pt = ak.Array([[43.1], []])
# mu_idx = ak.Array([[None, 0], []])
# mu_pt = mu_pt[:1]
# mu_idx = mu_idx[:1]
# print(mu_pt.layout)
# # print(repr(mu_pt))
# # print(repr(mu_idx))
# # print(
# #     mu_pt[
# #         ak.Array(
# #             [
# #                 [],
# #             ]
# #         )
# #     ]
# # )
from awkward.forms import IndexedForm, IndexedOptionForm, ListOffsetForm, NumpyForm

array = np.array
mu_pt = ak.from_buffers(
    ListOffsetForm("i64", NumpyForm("float64", form_key="node1"), form_key="node0"),
    1,
    {"node0-offsets": array([0, 1]), "node1-data": array([43.05972742])},
)

mu_idx = ak.from_buffers(
    IndexedForm(
        "i64",
        ListOffsetForm(
            "i64",
            IndexedOptionForm(
                "i64", NumpyForm("int64", form_key="node3"), form_key="node2"
            ),
            form_key="node1",
        ),
        form_key="node0",
    ),
    1,
    {
        "node0-index": array([65]),
        "node1-offsets": array(
            [
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                3,
                3,
                4,
                4,
                5,
                5,
                6,
                7,
                7,
                8,
                9,
                9,
                10,
                10,
                11,
                11,
                12,
                12,
                12,
                13,
                13,
                14,
                14,
                14,
                15,
                15,
                15,
                15,
                15,
                15,
                16,
                16,
                16,
                16,
                17,
                18,
                18,
                19,
                19,
                20,
                21,
                21,
                22,
                23,
                24,
                24,
                24,
                25,
                26,
                26,
                26,
                27,
                27,
                28,
                29,
                30,
                31,
                32,
                34,
                34,
                34,
                34,
                34,
                35,
                35,
                35,
                36,
                36,
            ]
        ),
        "node2-index": array(
            [
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                167,
                -1,
                -1,
            ]
        ),
        "node3-data": array(
            [
                22,
                29,
                21,
                67,
                0,
                32,
                30,
                29,
                21,
                47,
                53,
                35,
                38,
                204,
                13,
                33,
                110,
                46,
                30,
                5,
                64,
                29,
                42,
                185,
                6,
                26,
                55,
                10,
                26,
                158,
                145,
                26,
                31,
                31,
                49,
                8,
                40,
                56,
                5,
                38,
                8,
                26,
                25,
                24,
                6,
                25,
                42,
                33,
                24,
                136,
                14,
                50,
                6,
                29,
                8,
                10,
                40,
                50,
                10,
                33,
                40,
                32,
                10,
                28,
                46,
                15,
                46,
                16,
                33,
                11,
                38,
                29,
                67,
                26,
                60,
                50,
                30,
                45,
                70,
                27,
                499,
                22,
                81,
                24,
                33,
                5,
                35,
                43,
                37,
                62,
                20,
                30,
                55,
                24,
                23,
                25,
                26,
                97,
                14,
                42,
                24,
                37,
                40,
                28,
                8,
                29,
                176,
                51,
                52,
                25,
                310,
                59,
                13,
                136,
                33,
                57,
                0,
                26,
                23,
                13,
                37,
                24,
                68,
                6,
                32,
                151,
                41,
                6,
                45,
                61,
                76,
                17,
                12,
                8,
                6,
                78,
                57,
                48,
                21,
                27,
                42,
                28,
                73,
                24,
                33,
                77,
                19,
                36,
                75,
                77,
                42,
                28,
                22,
                34,
                42,
                31,
                9,
                34,
                12,
                34,
                79,
                7,
                0,
                1,
                0,
                0,
                0,
                0,
            ]
        ),
    },
)


print(mu_pt, mu_idx)
mu_idx = ak.to_packed(mu_idx)
print(ak.is_valid(mu_pt))
print(ak.is_valid(mu_idx))
print(mu_pt[mu_idx])
